### ISSUE TITLE
Scaling pixel-art sprites

### ISSUE THREAD

**Issue by PierreSavatte** [maarten-dp/arcade-curtains#3]
I have really small sprites (16x20). I wanted to scale them, but the result was softened.
Searched online and apparently it comes from the graphic API (OpenGL). There's a way to modify the filter used by `SpriteList.draw` ([from the official doc of arcade](https://arcade.academy/arcade.html#arcade.SpriteList.draw)) to avoid smoothing. 

So I would like to be able to set the filter. Since it's a parameter of the `BaseScene.actors.draw` method, maybe we can set the filter parameter while init the BaseScene (`opengl_filter=gl.GL_NEAREST`)

## Reproduce
With this workaround, we can see that adding the filter cancel the softening.
```python
class PixelArtScene(BaseScene):
    def draw(self, **kwargs):
        for slist in self._sprite_lists:
            # With softening:
            # slist.draw()
            # Without softening:
            slist.draw(filter=gl.GL_NEAREST)


class PlayerSprite(arcade.Sprite):
    def upscale(self, delta_time):
        self.scale += 0.25


class Scene(PixelArtScene):
    def setup(self):
        self.actors = arcade.SpriteList()

        # Set up the player
        self.player = PlayerSprite("<small_img_path>")
        self.actors.append(self.player)
        self.events.frame(self.player.upscale)
```

**Comment by maarten-dp** [comment]
Fixed in 0.4.0
