### ISSUE TITLE
Order of BaseScene._sprite_lists depending on definition order

### ISSUE THREAD

**Issue by PierreSavatte** [maarten-dp/arcade-curtains#4]
The current implementation of `BaseScene._setup_spritelists` is listing `_sprite_lists` in alphabetical order due to the use of the Python built-in `dir`, as stated [in the official documentation](https://docs.python.org/3/library/functions.html#dir): 
> The resulting list is sorted alphabetically

@maarten-dp We discussed it and you proposed to use `BaseScene.__dict__` instead, which is sorted by definition order

**Comment by maarten-dp** [comment]
Fixed in 0.4.0
